name = "flex"
main = "./src/controller/router.js"
compatibility_date="2025-08-05"
compatibility_flags = [ "nodejs_compat" ]

account_id = "2c3a662f1c50e7d9b72682cbfae3363c"
workers_dev = true

[[kv_namespaces]]
binding = "reminderList"
id = "7c5d87b1221b45ddb4bb93f84961d67b"

[[kv_namespaces]]
binding = "firBoundaries"
id = "822ff44da9b2493da2b519b20d25a8d4"

[triggers]
crons = [ "*/5 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_TEST_GUILD_ID
# DISCORD_APPLICATION_ID
# gsa_client_email
# gsa_client_id
# gsa_client_x509_cert_url
# gsa_private_key
# gsa_private_key_id
# service_account_key